### ISSUE TITLE
Nested rules

### ISSUE THREAD

**Issue by steinuil** [queer/boxxy#16]
I'm trying to clean up the mess of configuration directories left by VS Code and I was wondering if it would be possible to use "nested" rewrite rules. I tested with this configuration:

```yaml
rules:
- name: VS Code extension manifest
  mode: file
  target: ~/.vscode/extensions/extensions.json
  rewrite: ~/.config/vscode/extensions.json
- name: VS Code extensions
  mode: directory
  target: ~/.vscode/extensions
  rewrite: ~/.cache/vscode/extensions
```

And it looks like VS Code is using the file in ~/.cache/vscode/extensions/extensions.json despite the other rule being more "specific". It'd be nice if it was bound to ~/.config/vscode/extensions.json instead and that the rest of the files inside of extensions/ were bound to ~/.cache/vscode/extensions.

Would this be possible/not too complicated to implement in boxxy?

Thanks for the project btw, it's working great for me ❤️
