### ISSUE TITLE
Rules unexpectedly match based off of an unspecified context, even if the binary doesn't match

### ISSUE THREAD

**Issue by Afluttera** [queer/boxxy#44]
If you have a config with rules you want to match at any context, but only certain applications, it doesn't seem to work correctly. For example:
```yaml
  - name: "redirect ssh from ~/.ssh to ~/.config/ssh"
    target: "~/.ssh"
    rewrite: "~/.config/ssh"
    mode: "directory"
    only:
       - "/usr/bin/ssh"
       - "/usr/bin/rsync"
  - name: "test"
    target: "~/test1"
    rewrite: "~/test2"
    mode: "directory"
    only:
       - "/usr/bin/test"
```
Running `boxxy test` would also match against the `ssh` rule, because an unspecified context is treated as any context, which of course always matches, and that's all it takes for a rule to be considered matching.

The behavior I would expect is that if you specify an `only` restriction but not a `context` restriction, the `only` would take precedence. This effectively takes the behavior back to before the `context` feature existed if you don't use it, which maintains backwards compatibility with old configs as well.
