### ISSUE TITLE
Empty directories not deleted when boxxing Librewolf

### ISSUE THREAD

**Issue by thcrt** [queer/boxxy#55]
Librewolf creates `~/.librewolf` and `~/.mozilla`. Using boxxy, these are redirected to their set locations, but empty directories are still created at those paths.

---
**`boxxy.yaml`:**
```yaml
rules:
- name: Mozilla
  target: ~/.mozilla
  rewrite: ~/.local/config/mozilla
  mode: directory
- name: Librewolf
  target: ~/.librewolf
  rewrite: ~/.local/config/librewolf
```
